---
title: "Plots"
author: "Athena Tamayo Luisce"
date: "23/5/2021"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
setwd("/home/athena/Escritorio/CCG/4toSemestre/GenoHumana/Proyecto")
data <- read.table("PathogenicVariants.variant_function", sep = "\t", header = FALSE)
exons <- read.table("ExonicPathogenicVariants.variant_function", sep = "\t", header = FALSE)
```

```{r}
colnames(data) <- c("location", "gene", "description")
head(data)
```

```{r}
# create a dataframe of frecuencies 
freq <- as.data.frame(table(data$location))
# add the percentages 
freq$Perc <- round((freq$Freq)/sum(freq$Freq)*100, 2)
```

Plot the frequency of mutations associated with monogenic diseases located in different genomic regions.
```{r}
ggplot(freq, aes(x = Var1, y = log(Freq), fill = Var1)) +
  geom_bar(stat = "identity") +
  theme(axis.ticks.x = element_blank(),
        axis.text.x=element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.05),
        legend.title =  element_text(face = "bold")) +
  labs(title = "Frequency of mutations associated with monogenic diseases located 
                            in different genomic regions", x = NULL, y = "log(frequency)") +
  scale_fill_discrete(name = "Genomic location") +
  geom_text(aes(label = paste(Perc, "%", sep = "")), vjust = -0.2) 
```

Plot the frequency of the types of the type of mutations associated with monogenic diseases in exons 
```{r}
head(exons)
```
```{r}
mut <- as.data.frame(table(exons$V2))
mut$Perc <- round((mut$Freq)/sum(mut$Freq)*100, 2)
```

```{r}
ggplot(mut, aes(x = Var1, y = log(Freq), fill = Var1)) +
  geom_bar(stat = "identity") +
  theme(axis.ticks.x = element_blank(),
        axis.text.x=element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.05),
        legend.title =  element_text(face = "bold")) +
  labs(title = "Frequency of the type of mutations associated with monogenic 
                             diseases in exons",
       x = NULL, y = "log(frequency)") +
  scale_fill_discrete(name = "Type of mutations") +
  geom_text(aes(label = paste(Perc, "%", sep = "")), vjust = -0.2) +
  ylim(0, 10)
```

Split the description of the variants 
```{r}
elements <- strsplit(data$description, split = "[,]")
```

Plot the type of inheritance of the variants 
```{r}
inheritance <- vector()
for (i in 1:15633){
  inheritance <- c(inheritance, elements[[i]][3])
}

inheritance <- as.data.frame(table(inheritance))
inheritance$Perc <- round((inheritance$Freq)/sum(inheritance$Freq)*100, 2)
```

```{r}
ggplot(inheritance, aes(x = inheritance, y = log(Freq), fill = inheritance)) +
  geom_bar(stat = "identity") +
  theme(axis.ticks.x = element_blank(),
        axis.text.x=element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.05),
        legend.title =  element_text(face = "bold")) +
  labs(title = "Frequency of the type of inheritance of the variants",
       x = NULL, y = "log(frequency)") +
  scale_fill_discrete(name = "Type of inheritance") +
  geom_text(aes(label = paste(Perc, "%", sep = "")), vjust = -0.2) +
  ylim(0, 10)
```
