---
title: "FilterV"
author: "Edgar Leal"
date: "25/5/2021"
output: html_document
---

```{r}
library(tidyverse)#Regular Expressions
```


```{r}
InputData  <- read.table("C:/Users/yoroi/OneDrive/Escritorio/GenomicaHumana/HumanGenomicsProject/Monogenic2.avinput", header=F, sep=" ", quote="",fill=T)

```



```{r}

head(InputData)

#unique(InputData$V9)


InputData <- InputData[InputData$V9!="Multifactorial,"&
                         InputData$V9!="Isolated",]


#unique(InputData$V11)
#length(InputData$V1)
#Nos quedamos con 24530 variantes

```

```{r}
#unique(InputData$V12)
```

```{r}

#Filtrar las que sean pathogenic

text_p <- '(^pathogenic,|,pathogenic$|^pathogenic$|,pathogenic,)'
logic_P <- grepl(text_p,InputData$V12)
logic_P_1 <- grepl(text_p,InputData$V11)


#Filtrar las que no sean benign o likely benign

text_b <- 'benign'
logic_B <- grepl(text_b, InputData$V12)
logic_B_1 <- grepl(text_b, InputData$V11)

#Filtrar las que no sean uncertain-significance

text_u <- 'uncertain'
logic_U <- grepl(text_u, InputData$V12)
logic_U_1 <- grepl(text_u, InputData$V11)

#Filtrar las que no sean conflicting-interpretations of pathogenicity

text_c <- 'conflicting'
logic_C <- grepl(text_c, InputData$V12)
logic_C_1 <- grepl(text_c, InputData$V11)


#Filtrar las que no sean protective

text_pr <- 'protective'
logic_PR <- grepl(text_pr, InputData$V12)
logic_PR_1 <- grepl(text_pr, InputData$V11)

logical <- logic_P & !logic_B & !logic_U & !logic_C & !logic_PR
logical_1 <- logic_P_1 & !logic_B_1 & !logic_U_1 & !logic_C_1 & !logic_PR_1

pathogenic_0 <- InputData[logical,]
pathogenic_1 <- InputData[logical_1,]

pathogenic <- merge(pathogenic_0,pathogenic_1, all=T)
length(pathogenic$V11)
#Al final son 20237 variantes

#unique(pathogenic$V12)





```


```{r}
syn <- paste(paste(rep("chr",times=length(pathogenic$V1)), 
                 paste(pathogenic[,1], pathogenic[,2], sep = ":"), 
                 sep =""), pathogenic[,3], sep = "-")

df <- as.data.frame((table(syn)))

for (i in df[df$Freq!=1,1]){
  index <- which(syn == i)
    for (k in 1:length(index)){
      if (k!= 1){
        pathogenic[index[k],] <- NA
      }
    }
}
pathogenic <- na.omit(pathogenic)

#length(pathogenic$V1)
#Nos quedamos con 16781 variantes
```


```{r}
write.table(pathogenic, file="C:/Users/yoroi/OneDrive/Escritorio/GenomicaHumana/HumanGenomicsProject/Monogenic3.avinput", append=F, sep=" ", quote = F, row.names=F, col.names = F)

```

```{bash}
cd C:/Users/yoroi/OneDrive/Escritorio/GenomicaHumana/HumanGenomicsProject/
head Monogenic3.avinput
```
